version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai-trading-db
    environment:
      POSTGRES_USER: ai_trader
      POSTGRES_PASSWORD: trading_secret_2024
      POSTGRES_DB: ai_trading
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai-trading-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-trading-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - postgres
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - ai-trading-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-trading-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - ai-trading-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ai-trading-network:
    driver: bridge
