# Render Blueprint for AION Trading System
# This file enables one-click deployment to Render.com

services:
  # Backend API + WebSocket Server
  - type: web
    name: aion-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd iatrade/backend && npm install
    startCommand: cd iatrade/backend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: HYPERLIQUID_API_KEY
        sync: false
      - key: HYPERLIQUID_API_SECRET
        sync: false
      - key: HYPERLIQUID_API_URL
        value: https://api.hyperliquid.xyz
      - key: HYPERLIQUID_TESTNET
        value: true
      - key: INITIAL_BALANCE_PER_AI
        value: 200
      - key: TRADING_INTERVAL_SECONDS
        value: 45
      - key: MAX_POSITIONS_PER_AI
        value: 3
      - key: MAX_LEVERAGE
        value: 10
      - key: MAX_RISK_PER_TRADE_PERCENT
        value: 10
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: aion-frontend
    env: static
    region: oregon
    buildCommand: cd iatrade/frontend && npm install && npm run build
    staticPublishPath: ./iatrade/frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: aion-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_WS_URL
        fromService:
          type: web
          name: aion-backend
          envVarKey: RENDER_EXTERNAL_URL
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
